services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_NAME=question_rotation
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=question_rotation
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  postgres_data: